### ISSUE TITLE
fail with mocha --growl

### ISSUE THREAD

**Issue by guileen** [alex-seville/travis-cov#6]
`mocha --growl -R travis-cov`

```
TypeError: Cannot read property 'failures' of undefinedTypeError: Cannot read property 'failures' of undefined
    at Runner.<anonymous> (/Users/gl/workspace/node-mongoskin/node_modules/mocha/lib/mocha.js:189:14)
    at Runner.EventEmitter.emit (events.js:117:20)
    at /Users/gl/workspace/node-mongoskin/node_modules/mocha/lib/runner.js:584:10
    at /Users/gl/workspace/node-mongoskin/node_modules/mocha/lib/runner.js:518:7
    at next (/Users/gl/workspace/node-mongoskin/node_modules/mocha/lib/runner.js:247:23)
    at Object._onImmediate (/Users/gl/workspace/node-mongoskin/node_modules/mocha/lib/runner.js:276:5)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

**Comment by javatlacati** [comment]
some runners for mocha have the option

`growlOnSuccess: false`
